import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidenav from './Sidenav'
import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Container = ({ children }: React.PropsWithChildren) => {
  return <div className={styles.container}>{children}</div>
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Sidenav />
          {children}
        </Container>
      </body>
    </html>
  )
}
